before_install: chmod 777 assign_perm.sh
sudo: true
language: java		
java:		
 - 1.7		
script: "mvn install | tee -a /home/travis/mavin_logs.log"
install: sh install_dep.sh
branches:		
 only:		
 - master
after_install: sh war_deploy.sh
